In [ ]:
'''
Documentation:
Topic: Multi-Layer Perceptron (MLP) with iris dataset.
Dataset: url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
Methodology:
Part 1: 
Read and parse the initial dataset
Load it into our pandas dataframe
Display the dataset with feature information
Part 2: 
Split our dataset into its attributes and labels
Preprocessing the data
Part 3:
Perform feature scaling
Training and Predictions
Evaluating the Algorithm
'''

In [1]:
#importing all necessary libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
# Read dataset to pandas dataframe
irisdata= pd.read_csv(url, names=names)
# Display the dataset with feature information
irisdata.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
# Assign data from first four columns to X variable
X = irisdata.iloc[:, 0:4]
# Assign data from first fifth columns to y variable ('Class attribute')
y = irisdata.select_dtypes(include=[object])
print(y.head())
# unique values we have in our y series
y.Class.unique()

         Class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa


array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [4]:
# Let's convert these categorical values to numerical values. To do so we will use Scikit-Learn's LabelEncoder class
le = preprocessing.LabelEncoder()
y = y.apply(le.fit_transform)

In [5]:
# create training and test splits
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
# perform feature scaling
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
# Training and Predictions
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000) 
mlp.fit(X_train, y_train.values.ravel())
predictions = mlp.predict(X_test)

In [8]:
# Evaluating the Algorithm
predictions_train = mlp.predict(X_train)
print('Training predictions accuracy:',accuracy_score(predictions_train,y_train))
predictions_test = mlp.predict(X_test)
print('\nTesting predictions accuracy:',accuracy_score(predictions_test, y_test))
print('\nConfusion matrix:\n',confusion_matrix(y_test,predictions)) 
print('\nClassification report:\n',classification_report(y_test,predictions))
print('\nAccuracy Score on Confusion Matrix:',accuracy_score(y_test,predictions)) 
print('Error Score on Confusion Matrix:',1-accuracy_score(y_test,predictions))

Training predictions accuracy: 0.9833333333333333

Testing predictions accuracy: 0.9666666666666667

Confusion matrix:
 [[ 8  0  0]
 [ 0  7  1]
 [ 0  0 14]]

Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.88      0.93         8
           2       0.93      1.00      0.97        14

    accuracy                           0.97        30
   macro avg       0.98      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30


Accuracy Score on Confusion Matrix: 0.9666666666666667
Error Score on Confusion Matrix: 0.033333333333333326
